name: Build

on: [push]

defaults:
  run:
    shell: powershell

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1

    - name: Restore Packages
      run: nuget restore ./src/HDT.Plugins.Macaw.sln

    - name: Build Solution
      run: |
        msbuild.exe ./src/HDT.Plugins.Macaw.sln /p:GithubBuild="true" /p:Platform="Any CPU" /p:Configuration="Release"

  release:
    runs-on: ubuntu-latest
    needs: build
    
    steps:    
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.17.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: patch
        WITH_V: false